begin;

alter table public.evaluation_cycles
  add column if not exists cancelled_by uuid references auth.users(id) on delete set null,
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancellation_reason text,
  add column if not exists force_closed_by uuid references auth.users(id) on delete set null,
  add column if not exists force_closed_at timestamptz,
  add column if not exists force_close_reason text;

create table if not exists public.evaluation_cycle_governance_audit (
  id bigint generated by default as identity primary key,
  cycle_id bigint references public.evaluation_cycles(id) on delete set null,
  cycle_id_snapshot bigint not null,
  cycle_name text not null,
  action text not null check (action in ('paused', 'resumed', 'force_closed', 'cancelled', 'hard_deleted')),
  reason text not null check (length(trim(reason)) >= 5),
  previous_status text not null,
  next_status text,
  acted_by uuid not null references auth.users(id) on delete restrict,
  acted_at timestamptz not null default now()
);

create index if not exists evaluation_cycle_governance_audit_cycle_idx
  on public.evaluation_cycle_governance_audit (cycle_id_snapshot, acted_at desc);

alter table public.evaluation_cycle_governance_audit enable row level security;
revoke all on public.evaluation_cycle_governance_audit from anon, authenticated;
grant select on public.evaluation_cycle_governance_audit to authenticated;

drop policy if exists evaluation_cycle_governance_audit_read_admin on public.evaluation_cycle_governance_audit;
create policy evaluation_cycle_governance_audit_read_admin
  on public.evaluation_cycle_governance_audit for select to authenticated
  using (
    exists (
      select 1 from public.users u
      where u.auth_user_id = auth.uid() and u.active is true and u.sys_role::text = '관리자'
    )
  );

create or replace function public.assert_cycle_governance_actor(
  p_actor_id uuid,
  p_super_admin boolean default false
)
returns void language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_user public.users;
begin
  if p_actor_id is distinct from auth.uid() then raise exception 'Authenticated actor mismatch'; end if;
  select * into v_user from public.users where auth_user_id = p_actor_id and active is true;
  if not found or v_user.sys_role::text <> '관리자' then raise exception 'Administrator role required'; end if;
  if p_super_admin and lower(trim(v_user.email)) <> 'admin@cnhyex.com' then
    raise exception 'Super administrator role required';
  end if;
end $$;

create or replace function public.assert_cycle_governance_reason(p_reason text)
returns text language plpgsql immutable set search_path = public, pg_temp
as $$
declare v_reason text := trim(coalesce(p_reason, ''));
begin
  if length(v_reason) < 5 then raise exception 'A reason of at least 5 characters is required'; end if;
  return v_reason;
end $$;

create or replace function public.prevent_direct_cycle_status_transition()
returns trigger language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_transition text := current_setting('app.cycle_status_transition', true);
begin
  if new.status is not distinct from old.status then return new; end if;
  if old.status = '초안' and new.status = '진행중' and v_transition = 'activate' then return new; end if;
  if old.status = '진행중' and new.status = '일시정지' and v_transition = 'pause' then return new; end if;
  if old.status = '일시정지' and new.status = '진행중' and v_transition = 'resume' then return new; end if;
  if old.status in ('진행중', '일시정지') and new.status = '마감/보관됨'
     and v_transition in ('finalize', 'force_close') then return new; end if;
  if old.status in ('초안', '진행중', '일시정지') and new.status = '마감/보관됨'
     and v_transition in ('cancel', 'force_close') then return new; end if;
  raise exception 'Evaluation cycle status transitions must use the dedicated governance RPC';
end $$;

create or replace function public.prevent_weight_change_while_cycle_non_draft()
returns trigger language plpgsql security definer set search_path = public, pg_temp
as $$
begin
  if exists (
    select 1 from public.evaluation_cycles c
    where c.status not in ('마감/보관됨', 'closed', 'cancelled', 'archived')
      and (c.status is distinct from '초안' or c.internal_approval_status is distinct from 'not_requested')
  ) then
    raise exception 'Category weights are immutable while an active or approval-started evaluation cycle exists';
  end if;
  return new;
end $$;

create or replace function public.prevent_profile_classification_mutation_while_cycle_locked()
returns trigger language plpgsql security definer set search_path = public, pg_temp
as $$
begin
  if new.role is not distinct from old.role
     and new.company is not distinct from old.company
     and new.dept is not distinct from old.dept
     and new.workplace is not distinct from old.workplace
     and new.type is not distinct from old.type
     and new.is_evaluatee is not distinct from old.is_evaluatee
     and new.can_evaluate is not distinct from old.can_evaluate then
    return new;
  end if;
  if exists (
    select 1 from public.matchings m
    join public.evaluation_cycles c on c.id = m.cycle_id
    where (m.evaluator_id = old.id or m.target_id = old.id)
      and c.status not in ('마감/보관됨', 'closed', 'cancelled', 'archived')
      and (c.status is distinct from '초안' or c.internal_approval_status is distinct from 'not_requested')
  ) then
    raise exception 'Profile classification is immutable while the employee is assigned to an active or approval-started evaluation cycle';
  end if;
  return new;
end $$;

create or replace function public.governance_pause_cycle(
  p_cycle_id bigint, p_reason text, p_actor_id uuid
)
returns jsonb language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_cycle public.evaluation_cycles; v_reason text;
begin
  perform public.assert_cycle_governance_actor(p_actor_id, false);
  v_reason := public.assert_cycle_governance_reason(p_reason);
  select * into v_cycle from public.evaluation_cycles where id = p_cycle_id for update;
  if not found then raise exception 'Evaluation cycle not found'; end if;
  if v_cycle.status <> '진행중' then raise exception 'Only an active cycle can be paused'; end if;
  perform set_config('app.cycle_status_transition', 'pause', true);
  update public.evaluation_cycles set status = '일시정지', updated_at = now() where id = p_cycle_id;
  insert into public.evaluation_cycle_governance_audit
    (cycle_id, cycle_id_snapshot, cycle_name, action, reason, previous_status, next_status, acted_by)
  values (p_cycle_id, p_cycle_id, v_cycle.name, 'paused', v_reason, v_cycle.status, '일시정지', p_actor_id);
  return jsonb_build_object('cycle_id', p_cycle_id, 'status', '일시정지');
end $$;

create or replace function public.governance_resume_cycle(
  p_cycle_id bigint, p_reason text, p_actor_id uuid
)
returns jsonb language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_cycle public.evaluation_cycles; v_reason text;
begin
  perform public.assert_cycle_governance_actor(p_actor_id, false);
  v_reason := public.assert_cycle_governance_reason(p_reason);
  select * into v_cycle from public.evaluation_cycles where id = p_cycle_id for update;
  if not found then raise exception 'Evaluation cycle not found'; end if;
  if v_cycle.status <> '일시정지' then raise exception 'Only a paused cycle can be resumed'; end if;
  perform set_config('app.cycle_status_transition', 'resume', true);
  update public.evaluation_cycles set status = '진행중', updated_at = now() where id = p_cycle_id;
  insert into public.evaluation_cycle_governance_audit
    (cycle_id, cycle_id_snapshot, cycle_name, action, reason, previous_status, next_status, acted_by)
  values (p_cycle_id, p_cycle_id, v_cycle.name, 'resumed', v_reason, v_cycle.status, '진행중', p_actor_id);
  return jsonb_build_object('cycle_id', p_cycle_id, 'status', '진행중');
end $$;

create or replace function public.governance_force_close_cycle(
  p_cycle_id bigint, p_reason text, p_actor_id uuid
)
returns jsonb language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_cycle public.evaluation_cycles; v_reason text;
begin
  perform public.assert_cycle_governance_actor(p_actor_id, true);
  v_reason := public.assert_cycle_governance_reason(p_reason);
  select * into v_cycle from public.evaluation_cycles where id = p_cycle_id for update;
  if not found then raise exception 'Evaluation cycle not found'; end if;
  if v_cycle.status not in ('진행중', '일시정지') then raise exception 'Only an active or paused cycle can be force-closed'; end if;
  perform set_config('app.cycle_status_transition', 'force_close', true);
  update public.evaluation_cycles
  set status = '마감/보관됨', closed_by = p_actor_id, closed_at = now(),
      force_closed_by = p_actor_id, force_closed_at = now(), force_close_reason = v_reason,
      results_published = false, result_gate_open = false, updated_at = now()
  where id = p_cycle_id;
  insert into public.evaluation_cycle_governance_audit
    (cycle_id, cycle_id_snapshot, cycle_name, action, reason, previous_status, next_status, acted_by)
  values (p_cycle_id, p_cycle_id, v_cycle.name, 'force_closed', v_reason, v_cycle.status, '마감/보관됨', p_actor_id);
  return jsonb_build_object(
    'cycle_id', p_cycle_id, 'status', '마감/보관됨',
    'force_closed', true, 'results_published', false,
    'message', 'Force-closed cycles are retained without a publishable result snapshot'
  );
end $$;

create or replace function public.governance_cancel_cycle(
  p_cycle_id bigint, p_reason text, p_actor_id uuid, p_hard_delete boolean default false
)
returns jsonb language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_cycle public.evaluation_cycles; v_reason text; v_submitted integer;
begin
  perform public.assert_cycle_governance_actor(p_actor_id, true);
  v_reason := public.assert_cycle_governance_reason(p_reason);
  select * into v_cycle from public.evaluation_cycles where id = p_cycle_id for update;
  if not found then raise exception 'Evaluation cycle not found'; end if;
  if v_cycle.status = '마감/보관됨' then raise exception 'Historical cycles cannot be cancelled again'; end if;
  select count(*)::integer into v_submitted from public.evaluations where cycle_id = p_cycle_id;
  if p_hard_delete then
    if v_submitted > 0 then raise exception 'A cycle with submitted evaluations must be retained as a cancelled archive'; end if;
    insert into public.evaluation_cycle_governance_audit
      (cycle_id, cycle_id_snapshot, cycle_name, action, reason, previous_status, next_status, acted_by)
    values (p_cycle_id, p_cycle_id, v_cycle.name, 'hard_deleted', v_reason, v_cycle.status, null, p_actor_id);
    delete from public.evaluation_cycles where id = p_cycle_id;
    return jsonb_build_object('cycle_id', p_cycle_id, 'deleted', true);
  end if;
  perform set_config('app.cycle_status_transition', 'cancel', true);
  update public.evaluation_cycles
  set status = '마감/보관됨', closed_by = p_actor_id, closed_at = now(),
      cancelled_by = p_actor_id, cancelled_at = now(), cancellation_reason = v_reason,
      results_published = false, result_gate_open = false, updated_at = now()
  where id = p_cycle_id;
  update public.evaluation_cycle_approval_requests
  set request_status = 'cancelled', decided_by = p_actor_id, decided_at = now(),
      decision_note = v_reason, updated_at = now()
  where cycle_id = p_cycle_id and request_status = 'requested';
  insert into public.evaluation_cycle_governance_audit
    (cycle_id, cycle_id_snapshot, cycle_name, action, reason, previous_status, next_status, acted_by)
  values (p_cycle_id, p_cycle_id, v_cycle.name, 'cancelled', v_reason, v_cycle.status, '마감/보관됨', p_actor_id);
  return jsonb_build_object('cycle_id', p_cycle_id, 'status', '마감/보관됨', 'cancelled', true, 'submitted_evaluations', v_submitted);
end $$;

revoke all on function public.assert_cycle_governance_actor(uuid, boolean),
  public.assert_cycle_governance_reason(text),
  public.governance_pause_cycle(bigint, text, uuid),
  public.governance_resume_cycle(bigint, text, uuid),
  public.governance_force_close_cycle(bigint, text, uuid),
  public.governance_cancel_cycle(bigint, text, uuid, boolean)
from public;

grant execute on function public.governance_pause_cycle(bigint, text, uuid),
  public.governance_resume_cycle(bigint, text, uuid),
  public.governance_force_close_cycle(bigint, text, uuid),
  public.governance_cancel_cycle(bigint, text, uuid, boolean)
to authenticated;

commit;
