begin;

create table if not exists public.evaluation_matching_change_audit (
  id bigint generated by default as identity primary key,
  cycle_id bigint not null references public.evaluation_cycles(id) on delete cascade,
  evaluator_id bigint not null references public.users(id) on delete restrict,
  action text not null check (action in ('added', 'removed', 'replaced')),
  reason text not null check (length(trim(reason)) >= 5),
  before_state jsonb not null default '[]'::jsonb,
  after_state jsonb not null default '[]'::jsonb,
  acted_by uuid not null references auth.users(id) on delete restrict,
  acted_at timestamptz not null default now()
);

alter table public.evaluation_matching_change_audit enable row level security;
revoke all on public.evaluation_matching_change_audit from anon, authenticated;
grant select on public.evaluation_matching_change_audit to authenticated;
create policy evaluation_matching_change_audit_read_admin
  on public.evaluation_matching_change_audit for select to authenticated
  using (exists (
    select 1 from public.users u
    where u.auth_user_id = auth.uid() and u.active is true and u.sys_role::text = '관리자'
  ));

create or replace function public.prevent_non_draft_cycle_source_mutation()
returns trigger language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_cycle_id bigint; v_status text;
begin
  v_cycle_id := coalesce(new.cycle_id, old.cycle_id);
  select status into v_status from public.evaluation_cycles where id = v_cycle_id;
  if v_status = '초안' then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;
  if tg_table_name = 'matchings'
     and v_status = '일시정지'
     and current_setting('app.paused_matching_change', true) = 'allowed' then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;
  raise exception 'Questions and matchings are immutable outside draft; paused matching changes require the governance RPC';
end $$;

create or replace function public.governance_toggle_paused_matching(
  p_cycle_id bigint,
  p_evaluator_id bigint,
  p_target_id bigint,
  p_relationship_type text,
  p_reason text,
  p_actor_id uuid
)
returns jsonb language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_cycle public.evaluation_cycles;
  v_existing public.matchings;
  v_reason text;
  v_before jsonb;
  v_after jsonb;
  v_action text;
  v_inserted public.matchings;
  v_exists boolean;
begin
  perform public.assert_cycle_governance_actor(p_actor_id, false);
  v_reason := public.assert_cycle_governance_reason(p_reason);
  if p_evaluator_id = p_target_id then raise exception 'Self matching is not allowed'; end if;
  if p_relationship_type not in ('internal', 'exchange', 'leadership') then raise exception 'Invalid relationship type'; end if;
  select * into v_cycle from public.evaluation_cycles where id = p_cycle_id for update;
  if not found or v_cycle.status <> '일시정지' or v_cycle.internal_approval_status <> 'not_requested' then
    raise exception 'Only a paused cycle without approval activity can be rematched';
  end if;
  select * into v_existing from public.matchings
    where cycle_id = p_cycle_id and evaluator_id = p_evaluator_id and target_id = p_target_id
    for update;
  v_exists := found;
  v_before := case when v_exists then jsonb_build_array(to_jsonb(v_existing)) else '[]'::jsonb end;
  perform set_config('app.paused_matching_change', 'allowed', true);
  if v_exists then
    if exists (select 1 from public.evaluations where matching_id = v_existing.id) then
      raise exception 'A submitted matching cannot be removed';
    end if;
    delete from public.matchings where id = v_existing.id;
    v_after := '[]'::jsonb;
    v_action := 'removed';
  else
    insert into public.matchings
      (cycle_id,evaluator_id,target_id,type,relationship_type,updated_at)
    values
      (p_cycle_id,p_evaluator_id,p_target_id,'관리자 수동 지정',p_relationship_type,now())
    returning * into v_inserted;
    v_after := jsonb_build_array(to_jsonb(v_inserted));
    v_action := 'added';
  end if;
  insert into public.evaluation_matching_change_audit
    (cycle_id,evaluator_id,action,reason,before_state,after_state,acted_by)
  values (p_cycle_id,p_evaluator_id,v_action,v_reason,v_before,v_after,p_actor_id);
  return jsonb_build_object('cycle_id',p_cycle_id,'evaluator_id',p_evaluator_id,'action',v_action);
end $$;

create or replace function public.governance_replace_paused_matchings(
  p_cycle_id bigint,
  p_evaluator_id bigint,
  p_targets jsonb,
  p_reason text,
  p_actor_id uuid
)
returns jsonb language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_cycle public.evaluation_cycles;
  v_reason text;
  v_before jsonb;
  v_after jsonb;
begin
  perform public.assert_cycle_governance_actor(p_actor_id, false);
  v_reason := public.assert_cycle_governance_reason(p_reason);
  if jsonb_typeof(coalesce(p_targets, '[]'::jsonb)) <> 'array' then raise exception 'Targets must be an array'; end if;
  if exists (
    select 1 from jsonb_to_recordset(coalesce(p_targets, '[]'::jsonb)) x(target_id bigint, relationship_type text)
    where x.target_id is null or x.target_id = p_evaluator_id
       or x.relationship_type not in ('internal', 'exchange', 'leadership')
  ) then raise exception 'Invalid matching target'; end if;
  select * into v_cycle from public.evaluation_cycles where id = p_cycle_id for update;
  if not found or v_cycle.status <> '일시정지' or v_cycle.internal_approval_status <> 'not_requested' then
    raise exception 'Only a paused cycle without approval activity can be rematched';
  end if;
  select coalesce(jsonb_agg(to_jsonb(m) order by m.id), '[]'::jsonb) into v_before
    from public.matchings m where m.cycle_id = p_cycle_id and m.evaluator_id = p_evaluator_id;
  perform set_config('app.paused_matching_change', 'allowed', true);
  delete from public.matchings m
    where m.cycle_id = p_cycle_id and m.evaluator_id = p_evaluator_id
      and not exists (select 1 from public.evaluations e where e.matching_id = m.id)
      and not exists (
        select 1 from jsonb_to_recordset(coalesce(p_targets, '[]'::jsonb)) x(target_id bigint, relationship_type text)
        where x.target_id = m.target_id
      );
  insert into public.matchings (cycle_id,evaluator_id,target_id,type,relationship_type,updated_at)
    select p_cycle_id,p_evaluator_id,x.target_id,'관리자 수동 지정',x.relationship_type,now()
    from jsonb_to_recordset(coalesce(p_targets, '[]'::jsonb)) x(target_id bigint, relationship_type text)
    where not exists (
      select 1 from public.matchings m
      where m.cycle_id = p_cycle_id and m.evaluator_id = p_evaluator_id and m.target_id = x.target_id
    );
  select coalesce(jsonb_agg(to_jsonb(m) order by m.id), '[]'::jsonb) into v_after
    from public.matchings m where m.cycle_id = p_cycle_id and m.evaluator_id = p_evaluator_id;
  insert into public.evaluation_matching_change_audit
    (cycle_id,evaluator_id,action,reason,before_state,after_state,acted_by)
  values (p_cycle_id,p_evaluator_id,'replaced',v_reason,v_before,v_after,p_actor_id);
  return jsonb_build_object('cycle_id',p_cycle_id,'evaluator_id',p_evaluator_id,'matchings',v_after);
end $$;

create table if not exists public.evaluation_cycle_approval_steps (
  id bigint generated by default as identity primary key,
  approval_request_id bigint not null references public.evaluation_cycle_approval_requests(id) on delete cascade,
  step_order smallint not null check (step_order between 1 and 2),
  approver_id uuid not null references auth.users(id) on delete restrict,
  approver_user_id bigint not null references public.users(id) on delete restrict,
  status text not null default 'pending' check (status in ('pending','approved','rejected','skipped')),
  decided_at timestamptz,
  decision_note text,
  unique (approval_request_id, step_order),
  unique (approval_request_id, approver_id)
);

alter table public.evaluation_cycle_approval_steps enable row level security;
revoke all on public.evaluation_cycle_approval_steps from anon, authenticated;
grant select on public.evaluation_cycle_approval_steps to authenticated;
create policy evaluation_cycle_approval_steps_read_participant
  on public.evaluation_cycle_approval_steps for select to authenticated
  using (
    approver_id = auth.uid()
    or exists (
      select 1 from public.users u
      where u.auth_user_id = auth.uid() and u.active is true and u.sys_role::text = '관리자'
    )
  );

-- Legacy open requests had no approval line. Close them so an administrator can
-- submit a new request with an explicit ordered approver list.
update public.evaluation_cycle_approval_requests request
set request_status = 'cancelled',
    decided_at = now(),
    decision_note = 'Approval line migration: resubmission required',
    updated_at = now()
where request.request_status = 'requested'
  and not exists (
    select 1 from public.evaluation_cycle_approval_steps step
    where step.approval_request_id = request.id
  );

update public.evaluation_cycles cycle
set internal_approval_status = 'not_requested',
    internal_approval_completed_at = null,
    result_gate_open = false,
    updated_at = now()
where cycle.internal_approval_status = 'requested'
  and not exists (
    select 1
    from public.evaluation_cycle_approval_requests request
    where request.cycle_id = cycle.id
      and request.request_status = 'requested'
  );

drop function if exists public.governance_request_approval(bigint, uuid);
create function public.governance_request_approval(
  p_cycle_id bigint, p_actor_id uuid, p_approver_ids uuid[]
)
returns jsonb language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_role text; v_request public.evaluation_cycle_approval_requests; v_approver uuid; v_order integer := 0;
begin
  v_role := public.governance_actor_role(p_actor_id);
  if v_role <> '관리자' then raise exception 'Administrator role required'; end if;
  if p_approver_ids is null or cardinality(p_approver_ids) not between 1 and 2
     or cardinality(p_approver_ids) <> (select count(distinct x) from unnest(p_approver_ids) x)
     or p_actor_id = any(p_approver_ids) then raise exception 'One or two unique executive approvers are required'; end if;
  if exists (
    select 1 from unnest(p_approver_ids) x
    where not exists (
      select 1 from public.users u
      where u.auth_user_id = x and u.active is true and u.sys_role::text = '임원'
    )
  ) then raise exception 'Every approver must be an active executive'; end if;
  perform 1 from public.evaluation_cycles where id=p_cycle_id for update;
  if not found then raise exception 'Evaluation cycle not found'; end if;
  if not exists (select 1 from public.evaluation_archives where cycle_id=p_cycle_id) then raise exception 'Closed archive required'; end if;
  if exists (select 1 from public.evaluation_result_adjustments where cycle_id=p_cycle_id and status='active' and workflow_status <> 'second_stage_adjusted') then raise exception 'All active adjustments require stage 2 completion'; end if;
  insert into public.evaluation_cycle_approval_requests
    (cycle_id,request_status,requested_by,requested_at,result_version,created_at,updated_at)
  select p_cycle_id,'requested',p_actor_id,now(),result_version,now(),now()
    from public.evaluation_cycles where id=p_cycle_id returning * into v_request;
  foreach v_approver in array p_approver_ids loop
    v_order := v_order + 1;
    insert into public.evaluation_cycle_approval_steps
      (approval_request_id,step_order,approver_id,approver_user_id)
    select v_request.id,v_order,v_approver,u.id from public.users u where u.auth_user_id=v_approver;
  end loop;
  update public.evaluation_cycles set internal_approval_status='requested',result_gate_open=false,updated_at=now() where id=p_cycle_id;
  insert into public.evaluation_cycle_approval_audit
    (approval_request_id,cycle_id,action,acted_by,acted_at)
  values (v_request.id,p_cycle_id,'requested',p_actor_id,now());
  return jsonb_build_object('approval_request_id',v_request.id,'status','requested','approver_count',v_order);
end $$;

create or replace function public.governance_decide_approval(
  p_cycle_id bigint, p_approved boolean, p_reason text, p_actor_id uuid
)
returns jsonb language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_role text; v_request public.evaluation_cycle_approval_requests; v_step public.evaluation_cycle_approval_steps; v_complete boolean;
begin
  v_role := public.governance_actor_role(p_actor_id);
  if v_role <> '임원' then raise exception 'Executive role required'; end if;
  select * into v_request from public.evaluation_cycle_approval_requests
    where cycle_id=p_cycle_id and request_status='requested' for update;
  if not found then raise exception 'Pending approval request not found'; end if;
  if v_request.result_version is distinct from (select result_version from public.evaluation_cycles where id=p_cycle_id) then
    raise exception 'Approval request does not match the current result version';
  end if;
  select * into v_step from public.evaluation_cycle_approval_steps
    where approval_request_id=v_request.id and status='pending'
    order by step_order limit 1 for update;
  if not found or v_step.approver_id is distinct from p_actor_id then raise exception 'Only the current approval-line approver may decide'; end if;
  update public.evaluation_cycle_approval_steps
    set status=case when p_approved then 'approved' else 'rejected' end,
        decided_at=now(),decision_note=nullif(trim(coalesce(p_reason,'')),'')
    where id=v_step.id;
  if not p_approved then
    update public.evaluation_cycle_approval_steps set status='skipped'
      where approval_request_id=v_request.id and status='pending';
    update public.evaluation_cycle_approval_requests
      set request_status='rejected',decided_by=p_actor_id,decided_at=now(),
          decision_note=nullif(trim(coalesce(p_reason,'')),''),updated_at=now()
      where id=v_request.id;
    update public.evaluation_cycles set internal_approval_status='rejected',
      internal_approval_completed_at=now(),result_gate_open=false,updated_at=now() where id=p_cycle_id;
  else
    select not exists (
      select 1 from public.evaluation_cycle_approval_steps
      where approval_request_id=v_request.id and status='pending'
    ) into v_complete;
    if v_complete then
      update public.evaluation_cycle_approval_requests set request_status='approved',
        decided_by=p_actor_id,decided_at=now(),decision_note=nullif(trim(coalesce(p_reason,'')),''),
        updated_at=now() where id=v_request.id;
      update public.evaluation_cycles set internal_approval_status='approved',
        internal_approval_completed_at=now(),result_gate_open=true,updated_at=now() where id=p_cycle_id;
    end if;
  end if;
  insert into public.evaluation_cycle_approval_audit
    (approval_request_id,cycle_id,action,note,acted_by,acted_at)
  values (v_request.id,p_cycle_id,case when p_approved then 'approved' else 'rejected' end,
    nullif(trim(coalesce(p_reason,'')),''),p_actor_id,now());
  return jsonb_build_object('approval_request_id',v_request.id,'step_order',v_step.step_order,
    'status',case when not p_approved then 'rejected' when v_complete then 'approved' else 'requested' end);
end $$;

create or replace function public.governance_recall_approval(
  p_cycle_id bigint, p_reason text, p_actor_id uuid
)
returns jsonb language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_role text; v_request public.evaluation_cycle_approval_requests; v_reason text;
begin
  v_role := public.governance_actor_role(p_actor_id);
  if v_role <> '관리자' then raise exception 'Administrator role required'; end if;
  v_reason := public.assert_cycle_governance_reason(p_reason);
  select * into v_request from public.evaluation_cycle_approval_requests
    where cycle_id=p_cycle_id and request_status='requested' for update;
  if not found then raise exception 'Pending approval request not found'; end if;
  if v_request.requested_by is distinct from p_actor_id then raise exception 'Only the request creator may recall approval'; end if;
  if exists (select 1 from public.evaluation_cycle_approval_steps where approval_request_id=v_request.id and decided_at is not null) then
    raise exception 'Approval cannot be recalled after the first decision';
  end if;
  update public.evaluation_cycle_approval_steps set status='skipped'
    where approval_request_id=v_request.id and status='pending';
  update public.evaluation_cycle_approval_requests
    set request_status='cancelled',decided_by=p_actor_id,decided_at=now(),decision_note=v_reason,updated_at=now()
    where id=v_request.id;
  update public.evaluation_cycles set internal_approval_status='not_requested',
    internal_approval_completed_at=null,result_gate_open=false,updated_at=now() where id=p_cycle_id;
  insert into public.evaluation_cycle_approval_audit
    (approval_request_id,cycle_id,action,note,acted_by,acted_at)
  values (v_request.id,p_cycle_id,'cancelled',v_reason,p_actor_id,now());
  return jsonb_build_object('approval_request_id',v_request.id,'status','cancelled');
end $$;

revoke all on function public.governance_toggle_paused_matching(bigint,bigint,bigint,text,text,uuid),
  public.governance_replace_paused_matchings(bigint,bigint,jsonb,text,uuid),
  public.governance_request_approval(bigint,uuid,uuid[]),
  public.governance_decide_approval(bigint,boolean,text,uuid),
  public.governance_recall_approval(bigint,text,uuid)
from public;

grant execute on function public.governance_toggle_paused_matching(bigint,bigint,bigint,text,text,uuid),
  public.governance_replace_paused_matchings(bigint,bigint,jsonb,text,uuid),
  public.governance_request_approval(bigint,uuid,uuid[]),
  public.governance_decide_approval(bigint,boolean,text,uuid),
  public.governance_recall_approval(bigint,text,uuid)
to authenticated;

commit;
