begin;

create table if not exists public.password_reset_request_audit (
  id bigint generated by default as identity primary key,
  target_id bigint references public.users(id) on delete set null,
  email_hash text not null,
  ip_hash text not null,
  requested_at timestamptz not null default now(),
  status text not null check (status in ('sent','failed','ignored')),
  error_message text
);

alter table public.password_reset_request_audit enable row level security;
revoke all on public.password_reset_request_audit from anon, authenticated;

create index if not exists password_reset_request_email_idx
  on public.password_reset_request_audit (email_hash, requested_at desc);
create index if not exists password_reset_request_ip_idx
  on public.password_reset_request_audit (ip_hash, requested_at desc);

commit;
