alter type public.cycle_status_type add value if not exists '일시정지';

begin;

alter table public.users
  add column if not exists can_evaluate boolean not null default true,
  add column if not exists is_evaluatee boolean not null default true;

alter table public.evaluation_cycles
  add column if not exists description text not null default '',
  add column if not exists deadline date,
  add column if not exists closed_by uuid references auth.users(id) on delete set null,
  add column if not exists closed_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

update public.evaluation_cycles
set deadline = end_date
where deadline is null;

-- Preserve the deadline that existed in the legacy UI for the live 2026 H1 cycle.
update public.evaluation_cycles
set deadline = date '2026-07-31'
where id = 1 and start_date = date '2026-06-01' and end_date = date '2026-06-30'
  and status = '진행중';

alter table public.evaluation_cycles
  alter column deadline set not null,
  drop constraint if exists valid_cycle_deadline;
alter table public.evaluation_cycles
  add constraint valid_cycle_deadline check (deadline >= end_date);

alter table public.evaluation_questions
  add column if not exists updated_at timestamptz not null default now();

alter table public.matchings
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists matchings_cycle_evaluator_target_uidx
  on public.matchings (cycle_id, evaluator_id, target_id);

create table if not exists public.evaluation_settings (
  id smallint primary key default 1 check (id = 1),
  performance_weight numeric(5,2) not null default 40 check (performance_weight between 0 and 100),
  collaboration_weight numeric(5,2) not null default 30 check (collaboration_weight between 0 and 100),
  growth_weight numeric(5,2) not null default 20 check (growth_weight between 0 and 100),
  harmony_weight numeric(5,2) not null default 10 check (harmony_weight between 0 and 100),
  auto_matching_enabled boolean not null default true,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint evaluation_settings_weight_sum check (
    abs(performance_weight + collaboration_weight + growth_weight + harmony_weight - 100) < 0.01
  )
);

insert into public.evaluation_settings (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.evaluation_archives (
  id bigint generated by default as identity primary key,
  cycle_id bigint not null unique references public.evaluation_cycles(id) on delete restrict,
  cycle_name text not null,
  closed_by uuid references auth.users(id) on delete set null,
  closed_by_name text not null,
  closed_at timestamptz not null default now(),
  snapshot jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.employee_goals (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  cycle_id bigint references public.evaluation_cycles(id) on delete set null,
  title text not null check (length(trim(title)) between 2 and 300),
  category text not null check (category in ('성과','협업','성장','조화')),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  feedback text,
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.evaluation_answers (
  id bigint generated by default as identity primary key,
  evaluation_id bigint not null references public.evaluations(id) on delete cascade,
  matching_id bigint not null references public.matchings(id) on delete cascade,
  question_id bigint not null references public.evaluation_questions(id) on delete cascade,
  score numeric not null check (score between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (evaluation_id, question_id)
);

create or replace function public.my_assigned_targets()
returns table (
  matching_id bigint, cycle_id bigint, target_id bigint, name text, dept text,
  workplace text, role text, employee_type text, company text, submitted boolean
)
language sql stable security definer set search_path = public, pg_temp
as $$
  select m.id, m.cycle_id, target.id, target.name, target.dept, target.workplace,
         target.role, target.type::text, target.company::text,
         exists (select 1 from public.evaluations e where e.matching_id = m.id)
  from public.matchings m
  join public.users evaluator on evaluator.id = m.evaluator_id
  join public.users target on target.id = m.target_id
  join public.evaluation_cycles c on c.id = m.cycle_id
  where evaluator.id = public.current_employee_id()
    and evaluator.active is true and evaluator.can_evaluate is true
    and target.active is true and target.is_evaluatee is true
    and current_date between c.start_date and c.deadline
    and c.status = '진행중'
$$;

create or replace function public.submit_evaluation(
  p_matching_id bigint, p_perf_score numeric, p_collab_score numeric,
  p_growth_score numeric, p_harmony_score numeric, p_comment text
)
returns bigint language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_evaluation_id bigint;
begin
  if p_perf_score not between 0 and 100 or p_collab_score not between 0 and 100
     or p_growth_score not between 0 and 100 or p_harmony_score not between 0 and 100 then
    raise exception 'Score must be between 0 and 100';
  end if;
  if length(trim(coalesce(p_comment, ''))) < 50 then
    raise exception 'Comment must contain at least 50 characters';
  end if;
  if not exists (
    select 1 from public.matchings m
    join public.evaluation_cycles c on c.id = m.cycle_id
    join public.users evaluator on evaluator.id = m.evaluator_id
    join public.users target on target.id = m.target_id
    where m.id = p_matching_id and evaluator.auth_user_id = auth.uid()
      and evaluator.active is true and evaluator.can_evaluate is true
      and target.active is true and target.is_evaluatee is true
      and current_date between c.start_date and c.deadline
      and c.status = '진행중'
  ) then
    raise exception 'The evaluation is not assigned, enabled, or open';
  end if;
  insert into public.evaluations (
    matching_id, cycle_id, evaluator_id, target_id, perf_score, collab_score,
    growth_score, harmony_score, qualitative_comment
  )
  select m.id, m.cycle_id, m.evaluator_id, m.target_id, p_perf_score,
         p_collab_score, p_growth_score, p_harmony_score, trim(p_comment)
  from public.matchings m where m.id = p_matching_id
  on conflict (matching_id) do update set
    perf_score = excluded.perf_score, collab_score = excluded.collab_score,
    growth_score = excluded.growth_score, harmony_score = excluded.harmony_score,
    qualitative_comment = excluded.qualitative_comment
  returning id into v_evaluation_id;
  return v_evaluation_id;
end $$;

create or replace function public.submit_evaluation_central(
  p_matching_id bigint, p_perf_score numeric, p_collab_score numeric,
  p_growth_score numeric, p_harmony_score numeric, p_comment text, p_answers jsonb
)
returns bigint language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_evaluation_id bigint;
  v_cycle_id bigint;
  v_target_track text;
  v_target_dept text;
begin
  select m.cycle_id,
         case
           when target.dept like '%정비%' then '정비사'
           when target.type::text = '팀장급' or target.role like '%팀장%' or target.role like '%부장%' then '팀장/부서장급'
           when target.workplace like '%영업소%' or target.dept like '%영업소%' then '영업소'
           else '본사 팀원급'
         end,
         target.dept
    into v_cycle_id, v_target_track, v_target_dept
  from public.matchings m
  join public.users target on target.id = m.target_id
  where m.id = p_matching_id;

  if v_cycle_id is null then
    raise exception 'The evaluation matching does not exist';
  end if;

  if exists (
    select 1
    from public.evaluation_questions q
    where q.cycle_id = v_cycle_id
      and q.required is true
      and (q.target_track = '기본 필수질문' or q.target_track = v_target_track)
      and (q.target_dept is null or q.target_dept = '전체' or v_target_dept like '%' || q.target_dept || '%')
      and not exists (
        select 1
        from jsonb_to_recordset(coalesce(p_answers, '[]'::jsonb)) as answer(question_id bigint, score numeric)
        where answer.question_id = q.id and answer.score between 1 and 5
      )
  ) then
    raise exception 'Every required evaluation question must be answered';
  end if;

  v_evaluation_id := public.submit_evaluation(
    p_matching_id, p_perf_score, p_collab_score, p_growth_score, p_harmony_score, p_comment
  );
  delete from public.evaluation_answers where evaluation_id = v_evaluation_id;
  insert into public.evaluation_answers (evaluation_id, matching_id, question_id, score)
  select v_evaluation_id, p_matching_id, answer.question_id, answer.score
  from jsonb_to_recordset(coalesce(p_answers, '[]'::jsonb)) as answer(question_id bigint, score numeric)
  join public.evaluation_questions q on q.id = answer.question_id
  join public.matchings m on m.id = p_matching_id and q.cycle_id = m.cycle_id
  where answer.score between 1 and 5
    and (q.target_track = '기본 필수질문' or q.target_track = v_target_track)
    and (q.target_dept is null or q.target_dept = '전체' or v_target_dept like '%' || q.target_dept || '%')
  on conflict (evaluation_id, question_id) do update
    set score = excluded.score, updated_at = now();
  return v_evaluation_id;
end $$;

alter table public.evaluation_settings enable row level security;
alter table public.evaluation_archives enable row level security;
alter table public.employee_goals enable row level security;
alter table public.evaluation_answers enable row level security;

revoke all privileges on table public.evaluation_settings from anon;
revoke all privileges on table public.evaluation_archives from anon;
revoke all privileges on table public.employee_goals from anon;
revoke all privileges on table public.evaluation_answers from anon;
revoke insert, update, delete on table public.evaluation_settings from authenticated;
revoke insert, update, delete on table public.evaluation_archives from authenticated;
revoke insert, update, delete on table public.employee_goals from authenticated;
revoke insert, update, delete on table public.evaluation_answers from authenticated;
grant select on table public.evaluation_settings to authenticated;
grant select on table public.evaluation_archives to authenticated;
grant select on table public.employee_goals to authenticated;
grant select on table public.evaluation_answers to authenticated;

drop policy if exists evaluation_settings_read_authenticated on public.evaluation_settings;
create policy evaluation_settings_read_authenticated
on public.evaluation_settings for select to authenticated using (true);

drop policy if exists evaluation_archives_read_privileged on public.evaluation_archives;
create policy evaluation_archives_read_privileged
on public.evaluation_archives for select to authenticated
using (public.current_user_is_privileged());

drop policy if exists employee_goals_read_self_or_privileged on public.employee_goals;
create policy employee_goals_read_self_or_privileged
on public.employee_goals for select to authenticated
using (user_id = public.current_employee_id() or public.current_user_is_privileged());

drop policy if exists evaluation_answers_read_owner_or_privileged on public.evaluation_answers;
create policy evaluation_answers_read_owner_or_privileged
on public.evaluation_answers for select to authenticated
using (
  exists (
    select 1 from public.matchings m
    where m.id = evaluation_answers.matching_id
      and m.evaluator_id = public.current_employee_id()
  ) or public.current_user_is_privileged()
);

revoke all on function public.submit_evaluation_central(bigint,numeric,numeric,numeric,numeric,text,jsonb) from public;
grant execute on function public.submit_evaluation_central(bigint,numeric,numeric,numeric,numeric,text,jsonb) to authenticated;
revoke execute on function public.submit_evaluation(bigint,numeric,numeric,numeric,numeric,text) from public;
revoke execute on function public.submit_evaluation(bigint,numeric,numeric,numeric,numeric,text) from authenticated;

do $$
declare table_name_to_add text;
begin
  foreach table_name_to_add in array array[
    'users','evaluation_cycles','evaluation_questions','matchings','evaluations',
    'evaluation_result_adjustments','ai_evaluation_reports','evaluation_settings','evaluation_archives','employee_goals','evaluation_answers'
  ] loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = table_name_to_add
    ) then
      execute format('alter publication supabase_realtime add table public.%I', table_name_to_add);
    end if;
  end loop;
end $$;

commit;
