create table if not exists public.relationship_notes (
  id bigint generated by default as identity primary key,
  subject_user_id bigint not null references public.users(id) on delete restrict,
  related_user_id bigint not null references public.users(id) on delete restrict,
  category text not null check (category in ('업무 접점', '협업 관찰', '반복 배정', '배제 검토', '기타')),
  note_text text not null check (char_length(trim(note_text)) between 10 and 2000),
  observed_on date not null,
  expires_on date,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_by uuid not null references auth.users(id) on delete restrict,
  updated_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (subject_user_id <> related_user_id),
  check (expires_on is null or expires_on >= observed_on)
);

create index if not exists relationship_notes_subject_idx
  on public.relationship_notes(subject_user_id, status, observed_on desc);
create index if not exists relationship_notes_related_idx
  on public.relationship_notes(related_user_id, status, observed_on desc);

create table if not exists public.relationship_note_audit (
  id bigint generated by default as identity primary key,
  note_id bigint not null,
  action text not null check (action in ('created', 'updated', 'deactivated', 'reactivated', 'hard_deleted')),
  old_record jsonb,
  new_record jsonb,
  acted_by uuid,
  acted_at timestamptz not null default now()
);

create index if not exists relationship_note_audit_note_idx
  on public.relationship_note_audit(note_id, acted_at desc);

create or replace function public.audit_relationship_note_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_action text;
  v_actor uuid;
begin
  if tg_op = 'INSERT' then
    v_action := 'created';
    v_actor := new.created_by;
    insert into public.relationship_note_audit(note_id, action, new_record, acted_by)
    values (new.id, v_action, to_jsonb(new), v_actor);
    return new;
  elsif tg_op = 'DELETE' then
    insert into public.relationship_note_audit(note_id, action, old_record, acted_by)
    values (old.id, 'hard_deleted', to_jsonb(old), old.updated_by);
    return old;
  end if;

  v_action := case
    when old.status = 'active' and new.status = 'inactive' then 'deactivated'
    when old.status = 'inactive' and new.status = 'active' then 'reactivated'
    else 'updated'
  end;
  insert into public.relationship_note_audit(note_id, action, old_record, new_record, acted_by)
  values (new.id, v_action, to_jsonb(old), to_jsonb(new), new.updated_by);
  return new;
end;
$$;

drop trigger if exists relationship_notes_audit_trigger on public.relationship_notes;
create trigger relationship_notes_audit_trigger
after insert or update or delete on public.relationship_notes
for each row execute function public.audit_relationship_note_change();

alter table public.relationship_notes enable row level security;
alter table public.relationship_note_audit enable row level security;
revoke all on public.relationship_notes from anon, authenticated;
revoke all on public.relationship_note_audit from anon, authenticated;
revoke all on function public.audit_relationship_note_change() from public, anon, authenticated;

comment on table public.relationship_notes is
  'Administrator-only relationship observations. Deliberately excluded from evaluation matching and scoring.';
comment on table public.relationship_note_audit is
  'Append-only audit history for administrator relationship observations.';
