-- Extend ordered internal approval from two to three executives and persist
-- personal in-app notifications for administrators and executives.

alter table public.evaluation_cycle_approval_steps
  drop constraint if exists evaluation_cycle_approval_steps_step_order_check;
alter table public.evaluation_cycle_approval_steps
  add constraint evaluation_cycle_approval_steps_step_order_check
  check (step_order between 1 and 3);

create table if not exists public.evaluation_notifications (
  id bigint generated by default as identity primary key,
  recipient_user_id bigint not null references public.users(id) on delete cascade,
  cycle_id bigint references public.evaluation_cycles(id) on delete cascade,
  source_audit_id bigint references public.evaluation_cycle_approval_audit(id) on delete cascade,
  notification_type text not null check (notification_type in ('approval_requested','approval_next','approval_completed','approval_rejected','approval_cancelled')),
  title text not null,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (source_audit_id, recipient_user_id)
);

create index if not exists evaluation_notifications_recipient_idx
  on public.evaluation_notifications (recipient_user_id, read_at, created_at desc);

alter table public.evaluation_notifications enable row level security;
revoke all on public.evaluation_notifications from anon, authenticated;

create or replace function public.create_evaluation_approval_notification()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_request public.evaluation_cycle_approval_requests;
  v_recipient bigint;
  v_type text;
  v_title text;
  v_message text;
begin
  if new.approval_request_id is null then return new; end if;
  select * into v_request from public.evaluation_cycle_approval_requests where id = new.approval_request_id;
  if not found then return new; end if;

  if new.action = 'requested' then
    select approver_user_id into v_recipient
    from public.evaluation_cycle_approval_steps
    where approval_request_id = new.approval_request_id and status = 'pending'
    order by step_order limit 1;
    v_type := 'approval_requested';
    v_title := '전자결재 요청';
    v_message := '새 평가 결과 결재 요청이 도착했습니다.';
  elsif new.action = 'approved' then
    select approver_user_id into v_recipient
    from public.evaluation_cycle_approval_steps
    where approval_request_id = new.approval_request_id and status = 'pending'
    order by step_order limit 1;
    if v_recipient is not null then
      v_type := 'approval_next';
      v_title := '전자결재 차례 도착';
      v_message := '이전 결재가 승인되어 결재 차례가 도착했습니다.';
    else
      select id into v_recipient from public.users where auth_user_id = v_request.requested_by limit 1;
      v_type := 'approval_completed';
      v_title := '전자결재 최종 승인';
      v_message := '요청한 평가 결과의 전자결재가 최종 승인되었습니다.';
    end if;
  elsif new.action in ('rejected', 'cancelled') then
    select id into v_recipient from public.users where auth_user_id = v_request.requested_by limit 1;
    v_type := case when new.action = 'rejected' then 'approval_rejected' else 'approval_cancelled' end;
    v_title := case when new.action = 'rejected' then '전자결재 반려' else '전자결재 요청 회수' end;
    v_message := coalesce(nullif(new.note, ''), v_title || ' 처리되었습니다.');
  else
    return new;
  end if;

  if v_recipient is not null then
    insert into public.evaluation_notifications
      (recipient_user_id, cycle_id, source_audit_id, notification_type, title, message)
    values
      (v_recipient, new.cycle_id, new.id, v_type, v_title, v_message)
    on conflict (source_audit_id, recipient_user_id) do nothing;
  end if;
  return new;
end $$;

drop trigger if exists evaluation_approval_notification_trigger on public.evaluation_cycle_approval_audit;
create trigger evaluation_approval_notification_trigger
after insert on public.evaluation_cycle_approval_audit
for each row execute function public.create_evaluation_approval_notification();

create or replace function public.governance_request_approval(
  p_cycle_id bigint, p_actor_id uuid, p_approver_ids uuid[]
)
returns jsonb language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_role text; v_request public.evaluation_cycle_approval_requests; v_approver uuid; v_order integer := 0;
begin
  v_role := public.governance_actor_role(p_actor_id);
  if v_role <> '관리자' then raise exception 'Administrator role required'; end if;
  if p_approver_ids is null or cardinality(p_approver_ids) not between 1 and 3
     or cardinality(p_approver_ids) <> (select count(distinct x) from unnest(p_approver_ids) x)
     or p_actor_id = any(p_approver_ids) then raise exception 'One to three unique executive approvers are required'; end if;
  if exists (
    select 1 from unnest(p_approver_ids) x
    left join public.users u on u.auth_user_id=x
    where u.id is null or u.active is not true or u.sys_role::text <> '임원'
  ) then raise exception 'Every approver must be an active executive'; end if;
  if not exists (
    select 1
    from public.evaluation_cycle_final_results r
    where r.cycle_id = p_cycle_id
      and r.result_version = (select c.result_version from public.evaluation_cycles c where c.id = p_cycle_id)
  ) then
    perform public.governance_finalize_cycle(p_cycle_id, p_actor_id);
  end if;
  if exists (
    select 1
    from public.evaluation_cycle_final_results r
    where r.cycle_id = p_cycle_id
      and r.result_version = (select c.result_version from public.evaluation_cycles c where c.id = p_cycle_id)
      and coalesce(r.approved_grade, r.relative_grade) is null
  ) then raise exception 'Final approved grades are required before approval request'; end if;
  select * into v_request from public.evaluation_cycle_approval_requests
    where cycle_id=p_cycle_id and request_status='requested' for update;
  if found then raise exception 'Approval already requested'; end if;
  insert into public.evaluation_cycle_approval_requests
    (cycle_id,request_status,requested_by,requested_at,result_version,created_at,updated_at)
  select id,'requested',p_actor_id,now(),result_version,now(),now()
  from public.evaluation_cycles where id=p_cycle_id returning * into v_request;
  if not found then raise exception 'Evaluation cycle not found'; end if;
  foreach v_approver in array p_approver_ids loop
    v_order := v_order + 1;
    insert into public.evaluation_cycle_approval_steps
      (approval_request_id,step_order,approver_id,approver_user_id)
    select v_request.id,v_order,v_approver,u.id from public.users u where u.auth_user_id=v_approver;
  end loop;
  update public.evaluation_cycles set internal_approval_status='requested',
    internal_approval_completed_at=null,result_gate_open=false,results_published=false,updated_at=now()
    where id=p_cycle_id;
  insert into public.evaluation_cycle_approval_audit
    (approval_request_id,cycle_id,action,acted_by,acted_at)
  values (v_request.id,p_cycle_id,'requested',p_actor_id,now());
  return jsonb_build_object(
    'approval_request_id',v_request.id,
    'status','requested',
    'result_version',v_request.result_version,
    'approver_count',v_order
  );
end $$;

revoke all on function public.governance_request_approval(bigint,uuid,uuid[]) from public;
grant execute on function public.governance_request_approval(bigint,uuid,uuid[]) to authenticated;
