begin;

alter table public.evaluation_result_adjustments
  add column if not exists status text not null default 'active'
    check (status in ('active', 'cancelled')),
  add column if not exists cancelled_by uuid references auth.users(id) on delete set null,
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancellation_reason text;

alter table public.evaluation_result_adjustments
  drop constraint if exists evaluation_result_adjustments_cancellation_check;

alter table public.evaluation_result_adjustments
  add constraint evaluation_result_adjustments_cancellation_check check (
    (status = 'active' and cancelled_by is null and cancelled_at is null and cancellation_reason is null)
    or
    (status = 'cancelled' and cancelled_at is not null and length(trim(cancellation_reason)) >= 10)
  );

create table if not exists public.evaluation_result_adjustment_events (
  id bigint generated by default as identity primary key,
  adjustment_id bigint references public.evaluation_result_adjustments(id) on delete set null,
  cycle_id bigint not null references public.evaluation_cycles(id) on delete cascade,
  target_id bigint not null references public.users(id) on delete cascade,
  event_type text not null check (event_type in ('created', 'updated', 'cancelled', 'reactivated')),
  previous_final_score numeric(5,2),
  next_final_score numeric(5,2),
  reason text not null check (length(trim(reason)) >= 10),
  acted_by uuid references auth.users(id) on delete set null,
  occurred_at timestamptz not null default now()
);

alter table public.evaluation_result_adjustment_events enable row level security;
revoke all privileges on table public.evaluation_result_adjustment_events from anon;
revoke insert, update, delete on table public.evaluation_result_adjustment_events from authenticated;
grant select on table public.evaluation_result_adjustment_events to authenticated;

drop policy if exists result_adjustment_events_read_privileged on public.evaluation_result_adjustment_events;
create policy result_adjustment_events_read_privileged
on public.evaluation_result_adjustment_events for select to authenticated
using (public.current_user_is_privileged());

create index if not exists evaluation_result_adjustment_events_target_cycle_idx
  on public.evaluation_result_adjustment_events (target_id, cycle_id, occurred_at desc);

alter table public.evaluation_result_adjustment_events replica identity full;
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'evaluation_result_adjustment_events'
  ) then
    alter publication supabase_realtime add table public.evaluation_result_adjustment_events;
  end if;
end $$;

commit;
