begin;

alter table public.evaluation_notifications
  drop constraint if exists evaluation_notifications_notification_type_check;
alter table public.evaluation_notifications
  add constraint evaluation_notifications_notification_type_check
  check (notification_type in (
    'assignment_created','collection_completed','approval_requested','approval_next',
    'approval_completed','approval_rejected','approval_cancelled','results_published'
  ));

alter table public.evaluation_notifications
  add column if not exists event_key text,
  add column if not exists target_view text,
  add column if not exists target_subtab text,
  add column if not exists push_status text not null default 'pending',
  add column if not exists push_attempt_count integer not null default 0,
  add column if not exists push_sent_at timestamptz,
  add column if not exists push_error text;

alter table public.evaluation_notifications
  drop constraint if exists evaluation_notifications_push_status_check;
alter table public.evaluation_notifications
  add constraint evaluation_notifications_push_status_check
  check (push_status in ('pending','sending','sent','failed','skipped'));

alter table public.evaluation_notifications
  drop constraint if exists evaluation_notifications_recipient_event_key;
alter table public.evaluation_notifications
  add constraint evaluation_notifications_recipient_event_key
  unique (recipient_user_id, event_key);

create table if not exists public.push_device_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token text not null unique,
  platform text not null check (platform in ('android')),
  device_id text,
  app_version text,
  active boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_device_tokens_user_active_idx
  on public.push_device_tokens (user_id, active);

alter table public.push_device_tokens enable row level security;
revoke all on public.push_device_tokens from anon, authenticated;

create or replace function public.create_evaluation_approval_notification()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_request public.evaluation_cycle_approval_requests;
  v_recipient bigint;
  v_type text;
  v_title text;
  v_message text;
  v_view text := 'closingmanage';
  v_subtab text := 'summary';
begin
  if new.approval_request_id is null then return new; end if;
  select * into v_request from public.evaluation_cycle_approval_requests where id = new.approval_request_id;
  if not found then return new; end if;

  if new.action = 'requested' then
    select approver_user_id into v_recipient
    from public.evaluation_cycle_approval_steps
    where approval_request_id = new.approval_request_id and status = 'pending'
    order by step_order limit 1;
    v_type := 'approval_requested';
    v_title := '전자결재 요청';
    v_message := '새 평가 결과 결재 요청이 도착했습니다.';
  elsif new.action = 'approved' then
    select approver_user_id into v_recipient
    from public.evaluation_cycle_approval_steps
    where approval_request_id = new.approval_request_id and status = 'pending'
    order by step_order limit 1;
    if v_recipient is not null then
      v_type := 'approval_next';
      v_title := '전자결재 차례 도착';
      v_message := '이전 결재가 승인되어 결재 차례가 도착했습니다.';
    else
      select id into v_recipient from public.users where auth_user_id = v_request.requested_by limit 1;
      v_type := 'approval_completed';
      v_title := '전자결재 최종 승인';
      v_message := '요청한 평가 결과의 전자결재가 최종 승인되었습니다.';
    end if;
  elsif new.action in ('rejected', 'cancelled') then
    select id into v_recipient from public.users where auth_user_id = v_request.requested_by limit 1;
    v_type := case when new.action = 'rejected' then 'approval_rejected' else 'approval_cancelled' end;
    v_title := case when new.action = 'rejected' then '전자결재 반려' else '전자결재 요청 회수' end;
    v_message := coalesce(nullif(new.note, ''), v_title || ' 처리되었습니다.');
  else
    return new;
  end if;

  if v_recipient is not null then
    insert into public.evaluation_notifications (
      recipient_user_id, cycle_id, source_audit_id, notification_type, title, message,
      event_key, target_view, target_subtab
    ) values (
      v_recipient, new.cycle_id, new.id, v_type, v_title, v_message,
      'approval_audit:' || new.id::text, v_view, v_subtab
    )
    on conflict (source_audit_id, recipient_user_id) do update set
      notification_type = excluded.notification_type,
      title = excluded.title,
      message = excluded.message,
      event_key = excluded.event_key,
      target_view = excluded.target_view,
      target_subtab = excluded.target_subtab;
  end if;
  return new;
end $$;

create or replace function public.claim_push_notifications(p_notification_ids bigint[])
returns setof public.evaluation_notifications
language sql
security definer
set search_path = public, pg_temp
as $$
  update public.evaluation_notifications
     set push_status = 'sending',
         push_attempt_count = push_attempt_count + 1,
         push_error = null
   where id = any(p_notification_ids)
     and push_status in ('pending','failed')
     and push_attempt_count < 3
  returning *;
$$;

revoke all on function public.claim_push_notifications(bigint[]) from public, anon, authenticated;

commit;
