begin;

alter table public.evaluation_cycles
  add column if not exists results_published boolean not null default false;

create table if not exists public.ai_evaluation_reports (
  id bigint generated by default as identity primary key,
  cycle_id bigint not null references public.evaluation_cycles(id) on delete cascade,
  target_id bigint not null references public.users(id) on delete cascade,
  source_evaluation_count integer not null check (source_evaluation_count > 0),
  perf_score numeric(5,2) not null check (perf_score between 0 and 100),
  collab_score numeric(5,2) not null check (collab_score between 0 and 100),
  growth_score numeric(5,2) not null check (growth_score between 0 and 100),
  harmony_score numeric(5,2) not null check (harmony_score between 0 and 100),
  total_score numeric(5,2) not null check (total_score between 0 and 100),
  report jsonb not null,
  status text not null default 'draft' check (status in ('draft', 'approved')),
  model text not null,
  generated_by uuid references auth.users(id) on delete set null,
  approved_by uuid references auth.users(id) on delete set null,
  generated_at timestamptz not null default now(),
  approved_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (cycle_id, target_id)
);

alter table public.ai_evaluation_reports enable row level security;
revoke all privileges on table public.ai_evaluation_reports from anon;
revoke insert, update, delete on table public.ai_evaluation_reports from authenticated;
grant select on table public.ai_evaluation_reports to authenticated;

drop policy if exists ai_reports_read_approved_self_or_privileged
  on public.ai_evaluation_reports;
create policy ai_reports_read_approved_self_or_privileged
on public.ai_evaluation_reports for select to authenticated
using (
  public.current_user_is_privileged()
  or (
    target_id = public.current_employee_id()
    and status = 'approved'
    and exists (
      select 1 from public.evaluation_cycles c
      where c.id = ai_evaluation_reports.cycle_id
        and c.results_published is true
    )
  )
);

create index if not exists ai_evaluation_reports_target_cycle_idx
  on public.ai_evaluation_reports (target_id, cycle_id);

commit;
