begin;

alter table public.users
  add column if not exists login_method text not null default 'email',
  add column if not exists login_id text,
  add column if not exists auth_email text,
  add column if not exists pin_enrolled boolean not null default false,
  add column if not exists pin_enrollment_token_hash text,
  add column if not exists pin_enrollment_expires_at timestamptz;

alter table public.users drop constraint if exists users_login_method_check;
alter table public.users add constraint users_login_method_check
  check (login_method in ('email', 'pin', 'none'));

create unique index if not exists users_login_id_unique
  on public.users (lower(login_id)) where login_id is not null;
create unique index if not exists users_auth_email_unique
  on public.users (lower(auth_email)) where auth_email is not null;
create unique index if not exists users_pin_enrollment_token_unique
  on public.users (pin_enrollment_token_hash) where pin_enrollment_token_hash is not null;

update public.users
set auth_email = email,
    login_id = coalesce(login_id, email),
    login_method = 'email'
where auth_email is null and email is not null;

create table if not exists public.pin_login_attempt_audit (
  id bigint generated by default as identity primary key,
  login_id_hash text not null,
  ip_hash text not null,
  attempted_at timestamptz not null default now(),
  status text not null check (status in ('success', 'failed', 'throttled'))
);

alter table public.pin_login_attempt_audit enable row level security;
revoke all privileges on table public.pin_login_attempt_audit from anon, authenticated;
create index if not exists pin_login_attempt_recent_idx
  on public.pin_login_attempt_audit (login_id_hash, attempted_at desc);
create index if not exists pin_login_attempt_ip_recent_idx
  on public.pin_login_attempt_audit (ip_hash, attempted_at desc);

commit;
