begin;

create table if not exists public.password_reset_email_audit (
  id bigint generated by default as identity primary key,
  target_id bigint not null references public.users(id) on delete cascade,
  target_email text not null,
  requested_by uuid references auth.users(id) on delete set null,
  requested_at timestamptz not null default now(),
  status text not null check (status in ('sent','failed')),
  error_message text
);

alter table public.password_reset_email_audit enable row level security;
revoke all privileges on table public.password_reset_email_audit from anon, authenticated;

create index if not exists password_reset_email_audit_target_idx
  on public.password_reset_email_audit (target_id, requested_at desc);

commit;
